src/Entity/Activity.php
<?php

namespace App\Entity;

use App\Repository\ActivityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @Vich\Uploadable
 */
#[ORM\Entity(repositoryClass: ActivityRepository::class)]
class Activity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 500)]
    private $details;

    #[ORM\Column(type: 'string', length: 255)]
    private $lieu;

    #[ORM\Column(type: 'integer')]
    private $nb_user_min;

    #[ORM\Column(type: 'integer')]
    private $nb_user_max;

    #[ORM\Column(type: 'string', length: 20)]
    private $level;

    #[ORM\Column(type: 'datetime')]
    private $date;

    #[ORM\Column(type: 'string', length: 2550, nullable: true)]
    private $image;

    /**
     * @Vich\UploadableField(mapping="activity_image", fileNameProperty="image")
     */
	private $imageFile;

    #[ORM\OneToOne(mappedBy: 'activity', targetEntity: Review::class, cascade: ['persist', 'remove'])]
    private $review;

    #[ORM\OneToOne(mappedBy: 'activity', targetEntity: Incident::class, cascade: ['persist', 'remove'])]
    private $incident;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'activities')]
    #[ORM\JoinColumn(nullable: false)]
    private $leader;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\ManyToOne(targetEntity: Sport::class, inversedBy: 'activities')]
    #[ORM\JoinColumn(nullable: false)]
    private $sport;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'activitiesParticipant')]
    private $users;

    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: Message::class)]
    private $messages;

    #[ORM\ManyToMany(targetEntity: User::class )]
    #[ORM\JoinTable(name: "request_participation")]
    private $requestParticipation;


    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->requestParticipation = new ArrayCollection();
		$this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDetails(): ?string
    {
        return $this->details;
    }

    public function setDetails(string $details): self
    {
        $this->details = $details;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getNbUserMin(): ?int
    {
        return $this->nb_user_min;
    }

    public function setNbUserMin(int $nb_user_min): self
    {
        $this->nb_user_min = $nb_user_min;

        return $this;
    }

    public function getNbUserMax(): ?int
    {
        return $this->nb_user_max;
    }

    public function setNbUserMax(int $nb_user_max): self
    {
        $this->nb_user_max = $nb_user_max;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setImageFile(File $imageFile)
    {
        $this->imageFile = $imageFile;
        $this->created_at = new \DateTime('now');

    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getReview(): ?Review
    {
        return $this->review;
    }

    public function setReview(Review $review): self
    {
        // set the owning side of the relation if necessary
        if ($review->getActivity() !== $this) {
            $review->setActivity($this);
        }

        $this->review = $review;

        return $this;
    }

    public function getIncident(): ?Incident
    {
        return $this->incident;
    }

    public function setIncident(Incident $incident): self
    {
        // set the owning side of the relation if necessary
        if ($incident->getActivity() !== $this) {
            $incident->setActivity($this);
        }

        $this->incident = $incident;

        return $this;
    }

    public function getLeader(): ?User
    {
        return $this->leader;
    }

    public function setLeader(?User $leader): self
    {
        $this->leader = $leader;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSport(): ?Sport
    {
        return $this->sport;
    }

    public function setSport(?Sport $sport): self
    {
        $this->sport = $sport;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setActivity($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getActivity() === $this) {
                $message->setActivity(null);
            }
        }

        return $this;
    }

	public function __toString()
               	{
               		return $this->id;
               	}

    /**
     * @return Collection<int, User>
     */
    public function getRequestParticipation(): Collection
    {
        return $this->requestParticipation;
    }

    public function addRequestParticipation(User $requestParticipation): self
    {
        if (!$this->requestParticipation->contains($requestParticipation)) {
            $this->requestParticipation[] = $requestParticipation;
        }

        return $this;
    }

    public function removeRequestParticipation(User $requestParticipation): self
    {
        $this->requestParticipation->removeElement($requestParticipation);

        return $this;
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Entity\Message;
use App\Entity\User;
use App\Form\ActivityType;
use App\Form\FilterActivitiesType;
use App\Form\MessageFormType;
use App\Repository\ActivityRepository;
use App\Repository\UserRepository;
use App\Services\mailerService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/activity')]
class ActivityController extends AbstractController
{
    #[Route('/', name: 'activity_index', methods: ['GET', 'POST'])]
    public function index(ActivityRepository $activityRepository, Request $request): Response
    {
		$form = $this->createForm(filterActivitiesType::class);
	    $form->handleRequest($request);

	    if ($form->isSubmitted() && $form->isValid()) {
		    $datas = $form->getData();
			$sport = $datas["sport"]->getId();
			$level = $datas["level"];
		    return $this->render('activity/index.html.twig', [
			    'activities' => $activityRepository->findBySomeCriteria($sport, $level),
			    'form' => $form->createView()
		    ]);
	    }
	    return $this->render('activity/index.html.twig', [
		    'activities' => $activityRepository->findAll(),
		    'form' => $form->createView()
	    ]);

    }

    #[Route('/new', name: 'activity_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $activity->setLeader($this->getUser());
                $entityManager->persist($activity);
                $entityManager->flush();
                return $this->redirectToRoute('activity_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('activity/new.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'activity_show', methods: ['GET'])]
    public function show(Activity $activity): Response
    {
		$user = $this->getUser();

	    if(!$user) {
			return $this->redirectToRoute('app_register');
	    }
		$isParticipant = false;

		foreach($activity->getUsers() as $participant){
			if($participant === $user) {
				$isParticipant = true;
				break;
			} else {
				$isParticipant = false;
			}
		}
		if ($isParticipant) {
			$this->denyAccessUnlessGranted('PARTICIPANT', $activity);
			return $this->redirectToRoute('activity_join', ["id" => $activity->getId()], Response::HTTP_SEE_OTHER);
		} elseif ($user === $activity->getLeader()) {
			$this->denyAccessUnlessGranted('LEADER', $activity);
			return $this->redirectToRoute('activity_join', ["id" => $activity->getId()], Response::HTTP_SEE_OTHER);
		} else {
			return $this->render('activity/show.html.twig', [
				'activity' => $activity,
			]);
		}
    }

    #[Route('/{id}/edit', name: 'activity_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Activity $activity, EntityManagerInterface $entityManager): Response
    {
	    $this->denyAccessUnlessGranted('LEADER', $activity);
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('activity_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('activity/edit.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'activity_delete', methods: ['POST'])]
    public function delete(Request $request, Activity $activity, EntityManagerInterface $entityManager): Response
    {
	    $this->denyAccessUnlessGranted('LEADER', $activity);
        if ($this->isCsrfTokenValid('delete'.$activity->getId(), $request->request->get('_token'))) {
            $entityManager->remove($activity);
            $entityManager->flush();
        }

        return $this->redirectToRoute('activity_index', [], Response::HTTP_SEE_OTHER);
    }

	#[Route('/join/{id}', name: 'activity_join', methods: ['GET', 'POST'])]
	public function joinActivity(Request $request, Activity $activity, EntityManagerInterface $entityManager,User $userCurrent, $id, mailerService $mailer): Response
	{

		$nbPartMax = $activity->getNbUserMax();
		$nbPartCurrent = $activity->getUsers();
		$user = $this->getUser();
		$leader = $activity->getLeader();

		if($user === $leader) {
			$this->denyAccessUnlessGranted('LEADER', $activity);
		} elseif($user) {
			$this->denyAccessUnlessGranted('PARTICIPANT', $activity);
		}

		//Si le leader accepte la demande :
		if ((count($nbPartCurrent) < $nbPartMax) && ($user !== $leader)) {
			$activity->addUser($user);
			$entityManager->persist($user);
			$entityManager->persist($activity);
			$entityManager->flush();
		}

		$messages = $activity->getMessages();

		$mess = new Message();
		$form = $this->createForm(MessageFormType::class, $mess);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$mess->setAuthor($user);
			$mess->setActivity($activity);
			$entityManager->persist($mess);
			$entityManager->flush();
			return $this->redirect($request->getUri());
		}

		if(!$user) {
			return $this->redirectToRoute('app_register');
		}

		return $this->renderForm('activity/show.html.twig', [
			'activity' => $activity,
			'form' => $form,
			'messages' => $messages,
		]);

	}

	#[Route('/request/{id}', name: 'activity_request', methods: ['GET', 'POST'])]
	public function requestActivity(Request $request, Activity $activity, EntityManagerInterface $entityManager, $id, mailerService $mailer): Response
	{
		$nbPartMax = $activity->getNbUserMax();
		$nbPartCurrent = $activity->getUsers();
		$leader = $activity->getLeader();
		$user = $this->getUser();

		if ((count($nbPartCurrent) < $nbPartMax) && ($user !== $leader)) {
			$activity->addRequestParticipation($user);
			$entityManager->persist($user);
			$entityManager->persist($activity);
			$entityManager->flush();
		}

		//envoi demande de participation au leader

		$activityId = $activity->getId();
		$hrefLeader = "http://127.0.0.1:8000/activity/join/".$activityId;

		$subject = 'Demande de participation à votre activité ';
		$content = '<h2>Bonjour '. $leader->getPrenom() .', </h2></br>
		Vous avez une demande de participation de la part de '.$user->getPrenom().' '.$user->getNom().'</br> 
		pour votre activité : ' . $activity->getTitle().'</br>
		Merci de lui envoyer votre réponse <a href="'.$hrefLeader.'">ici</a> :)';
		$mailer->sendEmail(to:$leader->getEmail(), subject: $subject, content: $content);

		//$this->addFlash('success', 'Votre demande de participation a bien été envoyée');

		return $this->renderForm('activity/show.html.twig', [
			'activity' => $activity,
			'requestParticipant' => $activity->getRequestParticipation()
		]);

	}

	#[Route('/join/{id}/{user}', name: 'user_accept', methods: ['GET', 'POST'])]
	public function acceptActivity(Request $request, Activity $activity, EntityManagerInterface $entityManager, mailerService $mailer, UserRepository $userRepository, $user): Response
	{
		$leader = $activity->getLeader();
		$user = $userRepository->find($user);
		$nbPartMax = $activity->getNbUserMax();
		$nbPartCurrent = $activity->getUsers();

		//ajout du participant au groupe + suppression de la liste de demande
		if ((count($nbPartCurrent) < $nbPartMax) && ($user !== $leader)) {
			$activity->removeRequestParticipation($user);
			$activity->addUser($user);
			$entityManager->persist($user);
			$entityManager->persist($activity);
			$entityManager->flush();
		}

		//Envoi du mail au participant
		$activityId = $activity->getId();
		$hrefParticipant = "http://127.0.0.1:8000/activity/join/".$activityId;

		$subject = 'Votre demande a été acceptée ! ';
		$content = '<h2>Bonjour '. $user->getPrenom() .', </h2></br>
		Votre demande de participation pour '.$activity->getTitle().' à été acceptée</br> 
		Vous avez maintenant accès à la page du groupe pour discuter avec les autres membres :  <a href="'.$hrefParticipant.'">ici </a> :)';

		$mailer->sendEmail(to: $user->getEmail(), subject: $subject, content: $content );

		$this->addFlash('success', 'Votre réponse de participation a bien été envoyée');


		$mess = new Message();
		$form = $this->createForm(MessageFormType::class, $mess);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$mess->setAuthor($user);
			$mess->setActivity($activity);
			$entityManager->persist($mess);
			$entityManager->flush();
			return $this->redirect($request->getUri());
		}
		return $this->redirectToRoute('activity_join' ,["id" => $activity->getId()]);

	}

	#[Route('/reject/{id}/{user}', name: 'user_reject', methods: ['GET', 'POST'])]
	public function rejectActivity(Request $request, Activity $activity, EntityManagerInterface $entityManager, $id, mailerService $mailer, UserRepository $userRepository, $user): Response
	{
		$user = $userRepository->find($user);

		//suppression de la liste de demande
		$activity->removeRequestParticipation($user);
		$entityManager->persist($user);
		$entityManager->persist($activity);
		$entityManager->flush();

		//Envoi du mail au participant
		$hrefParticipant = "http://127.0.0.1:8000/activity/";

		$subject = 'Votre demande a été refusée... ';
		$content = '<h2>Bonjour '. $user->getPrenom() .', </h2></br>
		Votre demande de participation pour '.$activity->getTitle().' à été refusée</br> 
		Vous pouvez peut être (re)trouver votre bonheur :  <a href="'.$hrefParticipant.'">ici </a> :)';

		$mailer->sendEmail(to: $user->getEmail(), subject: $subject, content: $content );

templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/activity/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

<div class="row justify-content-center login-page">
    <div class="col-md-8 col-12 form-col login pad-top">
        {{ form_start(form) }}
        <div class="row justify-content-center align-items-center">
            <div class="col-md-2 col-2 return-button">
                <a href="{{ path('activity_index') }}"><i class="fa-solid fa-circle-chevron-left"></i></a>
            </div>
            <div class="col-md-10 col-10">
                {% if(app.request.get('_route') == 'activity_edit') %}
                    <h1>Modifier mon évènement</h1>
                {% else %}
                <h1>Je crée mon évènement</h1>
                {% endif %}
            </div>
        </div>
        {{ form_row(form.title, {'label':false}) }} <br>
        {{ form_row(form.details, {'label':false}) }} <br>
        <div class="row g-2">
            <div class="col-sm-7">
                {{ form_row(form.lieu, {'label':false}) }} <br>
            </div>
            <div class="col-sm">
                {{ form_row(form.sport, {'label':false}) }} <br>
            </div>
        </div>

        <div class="row g-2 justify-content-center">
            <div class="col-sm-7">
                <div class="row number-part align-items-center">
                    {{ form_label(form.nb_user_min, 'Nombre de participant(s)') }}
                    {#  {{ form_row(form.nb_user_min, {'label': false, 'class': 'form-range', 'type': 'range', 'id':'customRange1', min:"0", max:"15", step:'1'}) }} <br>
                {{ form_row(form.nb_user_max, {'label': false, 'class': 'form-range', 'type': 'range', 'id':'customRange1', min:"0", max:"15", step:'1'}) }} #}
                    <div class="white-text col-md-1 col-2">entre</div>
                    {{ form_row(form.nb_user_min, {'label': false, 'attr': {'class' : 'user-nb-min'}}) }}
                    <div class="white-text col-md-1 col-2">et</div>
                    {{ form_row(form.nb_user_max, {'label': false, 'attr': {'class' : 'user-nb-min'}})}} <br>
                </div>
            </div>
            <div class="col-sm">
                {{ form_label(form.level, 'Niveau sportif') }}
                {{ form_row(form.level, {'label':false}) }} <br>
            </div>
        </div>
        <div class="row g-2 justify-content-center">
            <div class="col-sm-7">
        {{ form_row(form.imageFile, {'label':"importer une image d'illustration", 'type':'file', 'class':'form-control', 'id':'formFile'}) }} <br>
            </div>
            <div class="col-sm-4">
        {{ form_row(form.date, {'label':false}) }} <br>
            </div>
        </div>

<div class="row">
    <div class="col">
        <button class="btn btn-primary">{{ button_label|default("Créer l'évènement") }}</button>
    </div>

        {% if(app.request.get('_route') == 'activity_edit') %}
    <div class="col">
            {{ include('activity/_delete_form.html.twig') }}
        {% endif %}
    </div>
        {{ form_end(form) }}

</div>


    </div>
</div>

{% block javascripts %}
    <script type="text/javascript">
        var numberform = document.querySelectorAll('.number-part .form-group');
        numberform.forEach((e => {
                e.classList.add("col-md-3","offset-1","col-3","ms-2");
        }))
    </script>
{% endblock %}

templates/activity/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Activity{% endblock %}

{% block body %}

    {{ include('activity/_form.html.twig', {'button_label': 'Modifier'}) }}

{% endblock %}

templates/activity/filter.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<div class="row filter-row justify-content-center align-items-center">
    {{ form_start(form) }}
    <div class="row justify-content-around align-items-center">
        <div class="col-md-3 col-10 m-3">
            {{ form_row(form.sport, {'label': false}) }}
        </div>
        <div class="col-md-3 col-10 m-3">
            {{ form_row(form.level, {'label': false}) }}
        </div>
        <div class="col-md-3 col-10 m-3 text-center">
            <button type="submit" class="btn btn-primary"> Rechercher </button>
        </div>
    </div>
   {#  {{ form_row(form.date, {'label': false}) }}#}
    {{ form_end(form) }}
</div>

templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les évènements{% endblock %}

{% block body %}
    <div class="row justify-content-evenly events-block filter-page">
        <h1 class="pad-left">Les évènements du moment</h1>
        {{ include('activity/filter.html.twig') }}
        {% if activities|length == 0 %}
            <div class="row justify-content-center">
                <div class="col-md-10">
                    Aucun résultat pour votre recherche ...
                </div>
            </div>
        {% else %}
            {% for activity in activities %}
                {{ include('home/activity-card.html.twig') }}
            {% endfor %}
        {% endif %}
                <div class="row justify-content-center">
                    <div class="col-md-3 text-center m-3 propose-event">
                        <a href="{{ path('activity_new') }}" type="button" class="btn btn-primary btn-join">Proposer un évènement</a>
                    </div>
                </div>
            </div>

{% endblock %}

templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Activity{% endblock %}

{% block body %}
    {{ include('activity/_form.html.twig') }}
{% endblock %}

templates/activity/not-join.html.twig
<div class="row activity-details-row">
    <div class="col return-button">
        <a href="{{ path('activity_index') }}"><i class="fa-solid fa-circle-chevron-left"></i></a>
    </div>
</div>

<div class="row justify-content-center activity-desc-row">
    <div class="col-md-4 col-sm-7 col-11 order-last order-md-first text-center mt-3">
        {% if activity.image is not null and activity.sport is defined and activity.sport.id != 0 %}
            <img  src="{{vich_uploader_asset(activity,"imageFile")}}" class="img-fluid rounded activity-img" alt="...">
        {% else %}
            <img src="{{ asset('images/sports/'~activity.sport.imagesLink~'/'~activity.sport.imagesLink~'-'~(random(2)+1)~'.jpg') }}" class="img-fluid activity-img rounded" alt="">
        {% endif %}
    </div>
    <div class="col-md-6 col-sm-10 col-10">
        <div class="row">
            <div class="col-md-10 col-sm-10 col-8">
                <h2>
                    {{ activity.title }}
                    <a href="#" class="btn btn-success btn-sport btn-level btn-sm m-3" role="button" aria-disabled="true">{{ activity.level }}</a>
                </h2>
            </div>
            <div class="col-md-2 col-sm-2 col-1">
                {% set userid = 0 %}

                {# si le user est participant => boutton participe #}
                {% for participant in activity.users %}
                    {% if participant.id == app.user.id %}
                        {% set userid = participant.id %}
                        <a href="#" class="btn btn-success" role="button" aria-disabled="true">Participe</a>
                    {% endif %}
                {% endfor %}

                {# si le user à une demande en attente => bouton demande en cours #}
                {% for participant in activity.requestParticipation %}
                    {% if participant.id == app.user.id %}
                        {% set userid = participant.id %}
                        <a href="#" class="btn btn-warning" role="button" aria-disabled="true">Demande en cours...</a>
                    {% endif %}
                {% endfor %}

                {% if activity.leader and (activity.leader.id != app.user.id) and (userid != app.user.id) %}

                    {# si le user n'est pas participant => boutton rejoindre #}
                    <a href="{{ path('activity_request', {'id': activity.id}) }}" class="btn btn-primary" role="button" aria-disabled="true">Rejoindre</a>

                    {# si le user est le leader => boutton editer l'event #}
                {% elseif activity.leader and activity.leader.id == app.user.id %}
                    <a href="{{ path('activity_edit', {'id': activity.id}) }}" class="btn btn-sm btn-primary" role="button" aria-disabled="true">Modifier</a>

                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h4>
                    <i class="fa-solid fa-location-dot"></i> {{ activity.lieu }}
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col activity-details">
                {{ activity.details }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-5 activity-date"><i class="fa-solid fa-calendar-days"></i> Le {{ activity.date|date('d m Y') }} à {{ activity.date|date('H:i') }}</div>
            <div class="col-md-5 activity-users"><i class="fa-solid fa-user-group"></i> {{ activity.nbUserMin }} / {{ activity.nbUserMax }} participants</div>
            <div class="col-md-2 align-self-end">
                {% if activity.leader and activity.leader.id == app.user.id %}
                    {{ include('activity/_delete_form.html.twig') }}
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ activity.title }}{% endblock %}

{% block body %}
    {{ include('activity/not-join.html.twig') }}

    {% if (app.user == activity.leader) %}
        {{ include('activity/join.html.twig') }}
    {% endif %}
    {% for participant in activity.users  %}
        {% if (app.user == participant) %}
            {{ include('activity/join.html.twig') }}
        {% endif %}
    {% endfor %}
{% endblock %}